### ISSUE TITLE
[BUG] AutoCloseVideoOSD feature broken only on Android devices after updating from Kodi v19.1 to v19.2

### ISSUE THREAD

**Issue by inb4after** [marcelveldt/script.skin.helper.service#149]
I would like to ask for your help in investigating an issue with script.skin.helper.service in AuraMOD skin ([initial thread](https://github.com/SerpentDrago/skin.auramod/issues/207), [cont.](https://github.com/SerpentDrago/skin.auramod/issues/221)).

AuraMOD has always used `Skin.SetNumeric(SkinHelper.AutoCloseVideoOSD)` as recommended in the wiki. After updating Kodi from v19.1 to v19.2, the function to auto-close VideoOSD.xml has stopped working on Android devices. 

AFAIA it was working on Kodi v19.0 and v19.1, so maybe a change in v19.2 could have induced this bug.

This issue is inconsistent in nature and can be reproduced by restarting Kodi until it fixes/breaks itself (the function/feature can either be in a working state or broken state).

Through testing we find it doesn't seem to affect PC devices, only Android devices.

I'm thinking it could be related to this Skin Helper Service error, which also only appears on Android devices:

```
2021-12-20 18:20:05.725 T:8002  WARNING <general>: Skin Helper Service --> Exception details: Type: ImportError Value: This platform lacks a functioning sem_open implementation, therefore, the required synchronization primitives needed will not function, see issue 3770. Traceback: Traceback (most recent call last):
                                                     File "/data/user/0/org.xbmc.kodi/cache/apk/assets/python3.8/lib/python3.8/multiprocessing/synchronize.py", line 28, in <module>
                                                       from _multiprocessing import SemLock, sem_unlink
                                                   ImportError: cannot import name 'sem_unlink' from '_multiprocessing' (unknown location)
                                                   
                                                   During handling of the above exception, another exception occurred:
                                                   
                                                   Traceback (most recent call last):
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.skin.helper.service/resources/lib/kodi_monitor.py", line 63, in onNotification
                                                       self.reset_win_props()
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.skin.helper.service/resources/lib/kodi_monitor.py", line 129, in reset_win_props
                                                       self.metadatautils.process_method_on_list(self.win.clearProperty, self.all_window_props)
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.metadatautils/lib/metadatautils.py", line 302, in process_method_on_list
                                                       return self._process_method_on_list(*args, **kwargs)
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.metadatautils/lib/helpers/utils.py", line 232, in process_method_on_list
                                                       pool = ThreadPool()
                                                     File "/data/user/0/org.xbmc.kodi/cache/apk/assets/python3.8/lib/python3.8/multiprocessing/pool.py", line 925, in __init__
                                                       Pool.__init__(self, processes, initializer, initargs)
                                                     File "/data/user/0/org.xbmc.kodi/cache/apk/assets/python3.8/lib/python3.8/multiprocessing/pool.py", line 196, in __init__
                                                       self._change_notifier = self._ctx.SimpleQueue()
                                                     File "/data/user/0/org.xbmc.kodi/cache/apk/assets/python3.8/lib/python3.8/multiprocessing/context.py", line 113, in SimpleQueue
                                                       return SimpleQueue(ctx=self.get_context())
                                                     File "/data/user/0/org.xbmc.kodi/cache/apk/assets/python3.8/lib/python3.8/multiprocessing/queues.py", line 336, in __init__
                                                       self._rlock = ctx.Lock()
                                                     File "/data/user/0/org.xbmc.kodi/cache/apk/assets/python3.8/lib/python3.8/multiprocessing/context.py", line 67, in Lock
                                                       from .synchronize import Lock
                                                     File "/data/user/0/org.xbmc.kodi/cache/apk/assets/python3.8/lib/python3.8/multiprocessing/synchronize.py", line 30, in <module>
                                                       raise ImportError("This platform lacks a functioning sem_open" +
                                                   ImportError: This platform lacks a functioning sem_open implementation, therefore, the required synchronization primitives needed will not function, see issue 3770.
                                                   
2021-12-20 18:20:05.725 T:8002    ERROR <general>: Skin Helper Service --> Exception in resources.lib.kodi_monitor ! --> This platform lacks a functioning sem_open implementation, therefore, the required synchronization primitives needed will not function, see issue 3770.
```

Could this error in the kodi_monitor be affecting the ability of Skin Helper Service to detect whether VideoOSD.xml is open?

**Comment by Angelinas1** [comment]
I update metadatautils yesterday.....can you try with version version="1.0.44" , to fix your warning in log

 https://github.com/SerpentDrago/skin.auramod/issues/207 there write "fixed" with version shs 1.1.40
Is this fixed ?

**Comment by inb4after** [comment]
> I update metadatautils yesterday.....can you try with version version="1.0.44" , to fix your warning in log
> 
> [SerpentDrago/skin.auramod#207](https://github.com/SerpentDrago/skin.auramod/issues/207) there write "fixed" with version shs 1.1.40 Is this fixed ?

After the users updated Skin Helper Service, the feature started working again (wasn't working at all before updating to latest) but after further testing and Kodi restarts the feature works intermittently, so the issue was opened again.

I will ask the users affected to update metadatautils as well.

**Comment by inb4after** [comment]
@Angelinas1 Issue has been resolved by updating script.module.metadatautils.
